### ISSUE TITLE
PostgreSQL or MySQL support

### ISSUE THREAD

**Issue by johnny-silverhand** [VKCOM/kphp#10]
First of all, I want to thank you for your contribution to the community.
But why release a product to the public without the support of at least one database? I understand that you have self-written databases, but they are not available to the community. In General, it is sad that there is no support for PostgreSQL or MySQL. At this stage, this is a product to play a couple of times locally and forget about it.

**Comment by eugene536** [comment]
Thanks for the question, there is an explanation here
https://vkcom.github.io/kphp/kphp-client/working-with-external-db/

Also there is a Russian article with more precise details on habr
https://habr.com/ru/company/vk/blog/527420/

**Comment by KLUGGERDEV** [comment]
https://vkcom.github.io/kphp/kphp-client/working-with-external-db/

**Comment by quasilyte** [comment]
To elaborate on what @eugene536 said, I'll give a quote from the link he provided:

> This probably will be done in the future, but as of the first public release, it’s the main obstacle to applicability.
