### ISSUE TITLE
Is there an integration or out-of-the-box package for linux or windows ？

### ISSUE THREAD

**Issue by KingBes** [VKCOM/kphp#1062]

**Comment by DrDet** [comment]
Yes, for Linux you can get ready deb pacakge, see documentatinon [here](https://vkcom.github.io/kphp/kphp-basics/installation.html#install-kphp-from-deb-packages).
Windows currently is not supported, as stated [here](https://vkcom.github.io/kphp/kphp-basics/installation.html#install-kphp-for-windows).
