### ISSUE TITLE
Is there FFI support in kphp?

### ISSUE THREAD

**Issue by zjsxwc** [VKCOM/kphp#185]
The FFI ( https://www.php.net/manual/en/intro.ffi.php ) feature in php can let us use libraries written in different languages. 

so, is there FFI support in kphp?

**Comment by quasilyte** [comment]
Hello.

No, there is currently no stable ffi/extensions mechanism for the KPHP.

It's planned to have something in the future. We might take a look at the PHP `ffi` mechanisms and mimic that API.

**Comment by quasilyte** [comment]
Btw, KPHP does support FFI now.
It's not a 100% implementation, but it's enough to use some libraries already.
There is also a public backlog of features to be implemented in this issue tracker.
