### ISSUE TITLE
Добавать страница discussion 

### ISSUE THREAD

**Issue by ExtinctDrift19** [VKCOM/kphp#407]
Для общения

**Comment by i582** [comment]
> Для общения

У нас есть чатик в телеграмме (https://t.me/kphp_chat), можно прийти в него для общения :)

**Comment by Danil42Russia** [comment]
Enabled: https://github.com/VKCOM/kphp/discussions
But for communication it is better to use the chat in Telegram: https://t.me/kphp_chat
