### ISSUE TITLE
Different behaviour of casting array to int in PHP and KPHP

### ISSUE THREAD

**Issue by romsar** [VKCOM/kphp#888]
```php
echo (int)['test'];
```

Might be it is not good idea to cast array to int, but just in case i will create this issue.

**PHP output:**
1

**kPHP output:**
compilation error: conversion from string[] to f$intval is forbidden

**Comment by Tsygankov-Slava** [comment]
KPHP imposes some restrictions, unlike PHP.  We've a strict type system and mixing of types in particular. 
You can read about it [here](https://vkcom.github.io/kphp/kphp-language/static-type-system/type-casting.html).
