### ISSUE TITLE
cli mode bug on docker

### ISSUE THREAD

**Issue by diegogit03** [VKCOM/kphp#974]
The script:

```php
<?php

var_dump($argv);
```

The  run commad:

```
./kphp_out/cli test --user=root
```

The output:

```
[232][2024-03-29 23:51:10.718520 relogin.cpp  112] You are trying to run the script as root, if you are sure of this, specify the user explicitly with the command --user
```

Possible problem: The cli get argv just for the php script, the server script dont have this problem

**Comment by Tsygankov-Slava** [comment]
I suppose the `--Xkphp-options` flag should help you.
Run your program as follows: `./kphp_out/cli test --Xkphp-options --u root `

**Comment by diegogit03** [comment]
> I suppose the `--Xkphp-options` flag should help you. Run your program as follows: `./kphp_out/cli test --Xkphp-options --u root `
